### PR TITLE
Ui/monitor cluster page

### PR DESCRIPTION
**Pull request by bisht-richa**

### CODE REVIEW

**Comment by ayoub-belarbi** [comment]
@bisht-richa Any update about this pull request? It's still marked as WIP. Thanks

**Comment by bisht-richa** [comment]
@ayoub-belarbi Yes it is still in WIP. Need to fix a few things.

**Comment by bisht-richa** [comment]
@ayoub-belarbi PR is ready to review.

**Comment by ayoub-belarbi** [comment]
I think one of the objectives in the next milestone is to reduce the number of external modules and packages that we are using. For now we have a lot of security issues related to this and also managing this great number of packages is tedious.

**Pull request merged**
